[project]
name = "lbis-intiface-shim"
version = "0.1.0"
description = "The hackiest Buttplug integration you've ever seen in your life"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.11.18",
    "websockets>=15.0.1",
]
